name: Check Spelling
on: [push]
jobs:
  build:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.16.0
      name: Check Spelling